version: '3.1'

services:
  node:
    image: "node:16"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
    expose:
      - 8080
    ports:
      - 8888:8080
    command: "npm run serve"